server:
  port: 8761

eureka:
  dashboard:
    path: /myeuraka
  server:
    # 关闭保护机制
    #剔除失效服务间隔
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server






